// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYDjH9AhA6yXNRxz9rP24uPitB02Vc2EE',
    appId: '1:1046293668177:android:ee4c39da70d759b3b77370',
    messagingSenderId: '1046293668177',
    projectId: 'movielibrary-3e1eb',
    databaseURL: 'https://movielibrary-3e1eb-default-rtdb.firebaseio.com',
    storageBucket: 'movielibrary-3e1eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtUSU3JM87MsMFIc8c6uYN8n2XpnCSVqo',
    appId: '1:1046293668177:ios:d6fc46ac50af9a30b77370',
    messagingSenderId: '1046293668177',
    projectId: 'movielibrary-3e1eb',
    databaseURL: 'https://movielibrary-3e1eb-default-rtdb.firebaseio.com',
    storageBucket: 'movielibrary-3e1eb.appspot.com',
    iosBundleId: 'com.example.movielibrary',
  );

}